
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculServiceService", targetNamespace = "http://ws.example.org/", wsdlLocation = "http://localhost:8088/CalculService?wsdl")
public class CalculServiceService
    extends Service
{

    private final static URL CALCULSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULSERVICESERVICE_EXCEPTION;
    private final static QName CALCULSERVICESERVICE_QNAME = new QName("http://ws.example.org/", "CalculServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/CalculService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULSERVICESERVICE_WSDL_LOCATION = url;
        CALCULSERVICESERVICE_EXCEPTION = e;
    }

    public CalculServiceService() {
        super(__getWsdlLocation(), CALCULSERVICESERVICE_QNAME);
    }

    public CalculServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULSERVICESERVICE_QNAME, features);
    }

    public CalculServiceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULSERVICESERVICE_QNAME);
    }

    public CalculServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULSERVICESERVICE_QNAME, features);
    }

    public CalculServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculService
     */
    @WebEndpoint(name = "CalculServicePort")
    public CalculService getCalculServicePort() {
        return super.getPort(new QName("http://ws.example.org/", "CalculServicePort"), CalculService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculService
     */
    @WebEndpoint(name = "CalculServicePort")
    public CalculService getCalculServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.example.org/", "CalculServicePort"), CalculService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULSERVICESERVICE_EXCEPTION!= null) {
            throw CALCULSERVICESERVICE_EXCEPTION;
        }
        return CALCULSERVICESERVICE_WSDL_LOCATION;
    }

}
